command: ['streamlit', 'run', 'streamlit_app.py']
env:
  - name: 'DATABRICKS_TOKEN'
    valueFrom: 'DATABRICKS_TOKEN'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '4096060557666813' # Replace with your MLflow experiment ID
